### ISSUE TITLE
flatMap

### ISSUE THREAD

**Issue by Las-Wonho** [Las-Wonho/LazyPython#1]

**Comment by BasicNeural** [comment]
구현을 봤는데, map 구현이 flatMap을 구현한게 아닌가 싶네요
map이면 Effect 객체와 non Effect 객체를 합성 할 수 있어야되요

**Comment by Las-Wonho** [comment]
@BasicNeural 그렇군요! 이 설명을 듣고 어느정도 감이 왔습니다. 감사합니다!
